### PR TITLE
Validate if slug field exists on build instead of on construction

### LINKED ISSUE #33: Sluggable in Fluent
laravel-doctrine/fluent v1.1.1

``` php
// ProductMapping.php

// ...
$builder->string('slug')->sluggable(['title', 'code']);
// ...
```

Run `php artisan doctrine:migration:diff`, got error `No mapping found for field 'slug' on class 'App\Domain\Product'`.

But error gone after commenting https://github.com/laravel-doctrine/fluent/blob/1.1/src/Extensions/Gedmo/Sluggable.php#L98.

### PR DESCRIPTION
**Pull request by guiwoda**
Fixes #33

### CODE REVIEW

**Comment by jhaoda** [comment]
@patrickbrouwers thanks. What about 1.1.2?

**Comment by patrickbrouwers** [comment]
The fix is in 1.1.2 if that's what you mean.

**Comment by jhaoda** [comment]
@patrickbrouwers you released 1.0.2.

**Comment by patrickbrouwers** [comment]
ah yeah, sorry haha

**Pull request merged**
