### PR TITLE
Add support for doctrine/orm:2.9.5

### PR DESCRIPTION
**Pull request by adrorocker**

### CODE REVIEW

**Comment by eigan** [comment]
Thanks!

**Comment by adrorocker** [comment]
@eigan Thanks for merging this. Do you think you can make a release with this change? 

Thanks in advance.

**Comment by eigan** [comment]
@adrorocker Released now with 1.2.2, sorry for the delay.

**Comment by adrorocker** [comment]
@eigan thanks a lot. 🤘

**Pull request merged**
